/*
 * ipc_bench -- throughput and latency measurements for libipc.
 *
 * Everything runs in ONE process under the invoking UID, so the benchmark
 * needs no root and no lab setup.  Two contexts are registered in a private
 * scratch directory (mode 0700 -- the library refuses a socket in a directory
 * that is group- or world-writable) and each gets its own event-loop thread,
 * because a synchronous ipc_send() can only complete if the *sender's* socket
 * is being drained: the reply has to be read off it.
 *
 * Measured:
 *   post throughput   one-way datagrams/second across a payload sweep
 *   send round trip   per-call wall time, reported as percentiles
 *   broadcast cost    one datagram per live peer in the namespace
 *
 * Usage:
 *   ipc_bench [--msgs N] [--lat N] [--bcast N] [--size B] [--pool]
 *             [--json] [--keep] [--help]
 *
 * Exit status is 0 when every phase completed, non-zero otherwise.
 */

#include <errno.h>
#include <inttypes.h>
#include <pthread.h>
#include <sched.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include <ipc/ipc.h>

/* ------------------------------------------------------------------ */
/* small helpers                                                       */
/* ------------------------------------------------------------------ */

static char  *g_buf;          /* shared payload buffer */
static size_t g_buf_cap;

static uint64_t now_ns(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_sec * 1000000000ull + (uint64_t)ts.tv_nsec;
}

static void sleep_ms(unsigned ms)
{
    struct timespec ts;
    ts.tv_sec  = (time_t)(ms / 1000u);
    ts.tv_nsec = (long)(ms % 1000u) * 1000000L;
    nanosleep(&ts, NULL);
}

static int cmp_u64(const void *a, const void *b)
{
    uint64_t x = *(const uint64_t *)a;
    uint64_t y = *(const uint64_t *)b;
    return (x > y) - (x < y);
}

/* Value at percentile `p` (0..100) of an array already sorted ascending. */
static uint64_t pct_of(const uint64_t *sorted, size_t n, double p)
{
    size_t idx;

    if (n == 0) {
        return 0;
    }
    idx = (size_t)((p / 100.0) * (double)(n - 1) + 0.5);
    if (idx >= n) {
        idx = n - 1;
    }
    return sorted[idx];
}

/* ------------------------------------------------------------------ */
/* peers                                                               */
/* ------------------------------------------------------------------ */

typedef struct {
    ipc_ctx_t           *ctx;
    pthread_t            tid;
    int                  tid_valid;
    atomic_uint_fast64_t received;  /* messages handed to the handler */
    atomic_uint_fast64_t bytes;     /* payload bytes delivered */
    atomic_uint_fast64_t replies;   /* replies the handler emitted */
    int                  loop_rc;
} peer_t;

static void *loop_thread(void *arg)
{
    peer_t *p = (peer_t *)arg;

    p->loop_rc = ipc_run(p->ctx);
    return NULL;
}

/* Receiver handler: count everything, answer every request. */
static void rx_handler(const ipc_msg_t *msg, void *user)
{
    peer_t *p = (peer_t *)user;

    atomic_fetch_add(&p->received, 1);
    atomic_fetch_add(&p->bytes, msg->len);

    if (msg->type == IPC_TYPE_REQ) {
        if (ipc_reply(msg, msg->data, msg->len) == IPC_OK) {
            atomic_fetch_add(&p->replies, 1);
        }
    }
}

/* Sender handler: nothing should ever arrive here, but count it if it does. */
static void tx_handler(const ipc_msg_t *msg, void *user)
{
    peer_t *p = (peer_t *)user;

    (void)msg;
    atomic_fetch_add(&p->received, 1);
}

/* ------------------------------------------------------------------ */
/* fixture                                                             */
/* ------------------------------------------------------------------ */

static char g_dir[256];

static int write_config(char *out, size_t cap, const char *sock_rx,
                        const char *sock_tx)
{
    char  path[512];
    FILE *f;

    snprintf(path, sizeof(path), "%s/modules.conf", g_dir);
    f = fopen(path, "w");
    if (f == NULL) {
        fprintf(stderr, "bench: cannot write %s: %s\n", path, strerror(errno));
        return -1;
    }
    fprintf(f, "# generated by ipc_bench\n");
    fprintf(f, "bench bench_rx %u %s\n", (unsigned)getuid(), sock_rx);
    fprintf(f, "bench bench_tx %u %s\n", (unsigned)getuid(), sock_tx);
    if (fclose(f) != 0) {
        return -1;
    }
    snprintf(out, cap, "%s", path);
    return 0;
}

/* Rewrite the shared payload buffer to the requested size. */
static int set_payload(size_t n)
{
    if (n == 0 || n > IPC_PAYLOAD_HARD_MAX) {
        return -1;
    }
    if (n > g_buf_cap) {
        char *nb = realloc(g_buf, n);
        if (nb == NULL) {
            return -1;
        }
        g_buf     = nb;
        g_buf_cap = n;
    }
    memset(g_buf, 'x', n);
    return 0;
}

/* ------------------------------------------------------------------ */
/* phases                                                              */
/* ------------------------------------------------------------------ */

/* One-way throughput.  ipc_post() is non-blocking and reports IPC_ERR_AGAIN
 * when the peer's receive queue is full; we retry and report the retry count,
 * so the figure reads as "sustainable rate for a cooperative sender" rather
 * than "rate the kernel will absorb without back-pressure".
 *
 * `window` is the number of messages that may be in flight (posted but not yet
 * handed to a handler).  0 means unbounded, which is correct for INLINE
 * dispatch: the handler runs on the receive thread, so nothing can queue up
 * behind it.  POOL dispatch has a *bounded callback queue*, and a 200000
 * message blast simply overruns it -- the receiver then drops events and the
 * phase never reaches its target.  Rather than let drops quietly turn a
 * throughput number into fiction, the POOL caller passes a window smaller than
 * the callback queue and the sender waits for the receiver to catch up.  The
 * resulting figure is a real sustainable rate with zero loss. */
static int bench_post(peer_t *tx, peer_t *rx, size_t payload, uint64_t msgs,
                      uint64_t window, uint64_t *out_rate, uint64_t *out_eagain)
{
    const uint32_t event = 0x2000u;
    uint64_t       start, elapsed, sent = 0, again = 0;

    if (msgs == 0 || set_payload(payload) != 0) {
        return -1;
    }

    atomic_store(&rx->received, 0);
    atomic_store(&rx->bytes, 0);
    start = now_ns();

    while (sent < msgs) {
        int rc;

        if (window > 0) {
            while (sent - (uint64_t)atomic_load(&rx->received) >= window) {
                sched_yield();
            }
        }
        rc = ipc_post(tx->ctx, "bench_rx", event, g_buf, payload);

        if (rc == IPC_OK) {
            sent++;
        } else if (rc == IPC_ERR_AGAIN) {
            again++;
            /* Yield: spinning on sendto() would just steal the CPU the
             * receiver thread needs to drain the queue. */
            sched_yield();
        } else {
            fprintf(stderr, "bench: ipc_post failed: %s\n", ipc_strerror(rc));
            return -1;
        }
    }

    {
        uint64_t deadline = now_ns() + 30000000000ull; /* 30 s watchdog */
        while ((uint64_t)atomic_load(&rx->received) < msgs) {
            if (now_ns() > deadline) {
                fprintf(stderr,
                        "bench: receiver stalled at %" PRIu64 "/%" PRIu64
                        "\n",
                        (uint64_t)atomic_load(&rx->received), msgs);
                return -1;
            }
            sleep_ms(1);
        }
    }

    elapsed = now_ns() - start;
    if (elapsed == 0) {
        elapsed = 1;
    }
    *out_rate   = (uint64_t)((double)msgs * 1e9 / (double)elapsed);
    *out_eagain = again;
    return 0;
}

/* Synchronous round trip.  Each call blocks until the reply lands, so the
 * per-call time is a genuine request/response latency, not a one-way cost. */
static int bench_send(peer_t *tx, peer_t *rx, size_t payload, uint64_t rounds,
                      uint64_t *samples, uint64_t *out_again)
{
    const uint32_t event = 0x2001u;
    uint64_t       again = 0, i;
    char          *reply;

    (void)rx;
    if (rounds == 0 || set_payload(payload) != 0) {
        return -1;
    }
    reply = malloc(payload + IPC_HDR_SIZE);
    if (reply == NULL) {
        return -1;
    }

    for (i = 0; i < rounds; i++) {
        size_t reply_len = 0;
        uint64_t t0, t1;
        int      rc;

        t0 = now_ns();
        rc = ipc_send_timeout(tx->ctx, "bench_rx", event, g_buf, payload,
                              reply, payload + IPC_HDR_SIZE, &reply_len, 5000);
        t1 = now_ns();

        if (rc == IPC_ERR_AGAIN) {
            again++;
            i--;
            continue;
        }
        if (rc != IPC_OK) {
            fprintf(stderr, "bench: ipc_send failed: %s\n", ipc_strerror(rc));
            free(reply);
            return -1;
        }
        samples[i] = t1 - t0;
    }
    free(reply);
    *out_again = again;
    return 0;
}

/* Broadcast cost: one datagram per live peer in the namespace.
 *
 * Retries through IPC_ERR_AGAIN so that the delivered count is exactly
 * `rounds`.  Without that, a broadcast is dropped whenever the peer queue
 * happens to be full, the drain wait below then never reaches `rounds`, and
 * the phase reports a failure that is really just back-pressure -- the
 * broadcast API's documented "queue full => skip" behaviour, not a bug.
 *
 * `window` does the same job it does for bench_post, and is not optional in
 * POOL mode: ipc_broadcast() cannot signal callback-queue exhaustion, so a
 * 5000-round blast simply overruns the queue and the events are dropped. */
static int bench_broadcast(peer_t *tx, peer_t *rx, size_t payload,
                           uint64_t rounds, uint64_t window,
                           uint64_t *out_per_sec, uint64_t *out_again)
{
    const uint32_t event = 0x2002u;
    uint64_t       start, elapsed, done = 0, again = 0;

    if (rounds == 0 || set_payload(payload) != 0) {
        return -1;
    }

    atomic_store(&rx->received, 0);
    start = now_ns();
    while (done < rounds) {
        int rc;

        if (window > 0) {
            while (done - (uint64_t)atomic_load(&rx->received) >= window) {
                sched_yield();
            }
        }
        rc = ipc_broadcast(tx->ctx, event, g_buf, payload);

        if (rc >= 0) {
            done++;
            continue;
        }
        if (rc == IPC_ERR_AGAIN) {
            again++;
            sched_yield();
            continue;
        }
        fprintf(stderr, "bench: ipc_broadcast failed: %s\n", ipc_strerror(rc));
        return -1;
    }
    {
        uint64_t deadline = now_ns() + 15000000000ull; /* 15 s */
        while ((uint64_t)atomic_load(&rx->received) < rounds) {
            if (now_ns() > deadline) {
                fprintf(stderr,
                        "bench: broadcast did not fully drain (%" PRIu64
                        "/%" PRIu64 " delivered)\n",
                        (uint64_t)atomic_load(&rx->received), rounds);
                return -1;
            }
            sleep_ms(1);
        }
    }
    elapsed = now_ns() - start;
    if (elapsed == 0) {
        elapsed = 1;
    }
    *out_per_sec = (uint64_t)((double)rounds * 1e9 / (double)elapsed);
    *out_again   = again;
    return 0;
}

static void report_latency(const uint64_t *sorted, size_t n, int json)
{
    uint64_t sum = 0;
    size_t   i;

    for (i = 0; i < n; i++) {
        sum += sorted[i];
    }
    if (json) {
        printf("  \"latency_ns\": { \"n\": %zu, \"min\": %" PRIu64
               ", \"p50\": %" PRIu64 ", \"p90\": %" PRIu64
               ", \"p99\": %" PRIu64 ", \"p999\": %" PRIu64
               ", \"max\": %" PRIu64 ", \"mean\": %.1f },\n",
               n, sorted[0], pct_of(sorted, n, 50), pct_of(sorted, n, 90),
               pct_of(sorted, n, 99), pct_of(sorted, n, 99.9), sorted[n - 1],
               n ? (double)sum / (double)n : 0.0);
    } else {
        printf("  round trip  min %7" PRIu64 " ns   p50 %7" PRIu64
               " ns   p90 %7" PRIu64 " ns\n",
               sorted[0], pct_of(sorted, n, 50), pct_of(sorted, n, 90));
        printf("              p99 %7" PRIu64 " ns  p99.9 %7" PRIu64
               " ns   max %7" PRIu64 " ns   mean %9.1f ns\n",
               pct_of(sorted, n, 99), pct_of(sorted, n, 99.9), sorted[n - 1],
               n ? (double)sum / (double)n : 0.0);
    }
}

/* ------------------------------------------------------------------ */
/* main                                                                */
/* ------------------------------------------------------------------ */

static void usage(void)
{
    fprintf(stderr, "usage: ipc_bench [--msgs N] [--lat N] [--bcast N]"
                    " [--size B]\n"
                    "                 [--pool] [--window N] [--json] [--keep]"
                    " [--help]\n");
}

int main(int argc, char **argv)
{
    ipc_register_opts_t opts = IPC_REGISTER_OPTS_INIT;
    peer_t              rx = { 0 };
    peer_t              tx = { 0 };
    uint64_t            msgs = 200000, lat_rounds = 20000, bcast_rounds = 5000;
    size_t              payload = 256;
    uint64_t            window = 0;
    int                 use_pool = 0, json = 0, keep = 0, rc = 1, i;
    char                conf[512] = { 0 }, sock_rx[512] = { 0 },
                        sock_tx[512] = { 0 };
    char                tmpl[] = "/tmp/ipc-bench-XXXXXX";
    uint64_t           *lat_buf = NULL;
    static const size_t sizes[] = { 64, 256, 1024, 8192, 60000 };

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--msgs") == 0 && i + 1 < argc) {
            msgs = strtoull(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--lat") == 0 && i + 1 < argc) {
            lat_rounds = strtoull(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--bcast") == 0 && i + 1 < argc) {
            bcast_rounds = strtoull(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--size") == 0 && i + 1 < argc) {
            payload = (size_t)strtoull(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--pool") == 0) {
            use_pool = 1;
        } else if (strcmp(argv[i], "--window") == 0 && i + 1 < argc) {
            window = strtoull(argv[++i], NULL, 10);
        } else if (strcmp(argv[i], "--json") == 0) {
            json = 1;
        } else if (strcmp(argv[i], "--keep") == 0) {
            keep = 1;
        } else if (strcmp(argv[i], "--help") == 0 ||
                   strcmp(argv[i], "-h") == 0) {
            usage();
            return 0;
        } else {
            fprintf(stderr, "bench: unknown argument '%s'\n", argv[i]);
            usage();
            return 2;
        }
    }
    if (payload == 0 || payload > IPC_PAYLOAD_HARD_MAX) {
        fprintf(stderr, "bench: payload must be 1..%u\n", IPC_PAYLOAD_HARD_MAX);
        return 2;
    }

    if (mkdtemp(tmpl) == NULL) {
        fprintf(stderr, "bench: mkdtemp: %s\n", strerror(errno));
        return 1;
    }
    snprintf(g_dir, sizeof(g_dir), "%s", tmpl);

    snprintf(sock_rx, sizeof(sock_rx), "%s/rx.sock", g_dir);
    snprintf(sock_tx, sizeof(sock_tx), "%s/tx.sock", g_dir);
    if (write_config(conf, sizeof(conf), sock_rx, sock_tx) != 0) {
        goto out_scratch;
    }

    opts.ns           = "bench";
    opts.conf_path    = conf;
    opts.max_payload  = IPC_PAYLOAD_HARD_MAX;
    opts.max_pending  = 64;
    opts.workers      = 2;
    opts.cb_queue_max = 256;
    opts.dispatch     = use_pool ? IPC_DISPATCH_POOL : IPC_DISPATCH_INLINE;

    /* POOL dispatch buffers deliveries in a bounded callback queue, so the
     * sender has to stay inside it.  Keeping the window at a quarter of the
     * queue leaves room for the workers to be scheduled without the receiver
     * ever having to drop an event. */
    if (window == 0 && use_pool) {
        window = (uint64_t)opts.cb_queue_max / 4u;
    }
    /* An explicit --window above the queue depth would silently push
     * cb_dropped off zero, which invalidates the "zero loss" reading of the
     * throughput table.  Clamp loudly instead of reporting a rate that was
     * bought with dropped events. */
    if (window > 0 && window > (uint64_t)opts.cb_queue_max) {
        fprintf(stderr,
                "bench: --window %" PRIu64 " exceeds the callback queue depth "
                "(%d); clamping to %d\n",
                window, opts.cb_queue_max, opts.cb_queue_max);
        window = (uint64_t)opts.cb_queue_max;
    }

    opts.module = "bench_rx";
    rc = ipc_register(&opts, &rx.ctx);
    if (rc != IPC_OK) {
        fprintf(stderr, "bench: register bench_rx failed: %s\n",
                ipc_strerror(rc));
        rc = 1;
        goto out_scratch;
    }
    opts.module = "bench_tx";
    rc = ipc_register(&opts, &tx.ctx);
    if (rc != IPC_OK) {
        fprintf(stderr, "bench: register bench_tx failed: %s\n",
                ipc_strerror(rc));
        rc = 1;
        goto out_unreg_rx;
    }
    if (ipc_set_handler(rx.ctx, rx_handler, &rx) != IPC_OK ||
        ipc_set_handler(tx.ctx, tx_handler, &tx) != IPC_OK) {
        fprintf(stderr, "bench: ipc_set_handler failed\n");
        rc = 1;
        goto out_unreg_both;
    }

    rx.tid_valid = (pthread_create(&rx.tid, NULL, loop_thread, &rx) == 0);
    if (!rx.tid_valid) {
        fprintf(stderr, "bench: cannot start the receiver loop\n");
        rc = 1;
        goto out_unreg_both;
    }
    tx.tid_valid = (pthread_create(&tx.tid, NULL, loop_thread, &tx) == 0);
    if (!tx.tid_valid) {
        fprintf(stderr, "bench: cannot start the sender loop\n");
        rc = 1;
        goto out_stop;
    }

    if (!json) {
        printf("ipc_bench  dispatch=%s  uid=%u  in-flight window=%" PRIu64 "\n",
               use_pool ? "pool" : "inline", (unsigned)getuid(), window);
        printf("  scratch %s\n", g_dir);
        printf("\n-- one-way throughput (ipc_post, %" PRIu64 " messages)\n",
               msgs);
    } else {
        printf("{\n  \"dispatch\": \"%s\",\n  \"messages\": %" PRIu64 ",\n",
               use_pool ? "pool" : "inline", msgs);
        printf("  \"throughput\": [\n");
    }

    for (size_t k = 0; k < sizeof(sizes) / sizeof(sizes[0]); k++) {
        size_t   probe = sizes[k] > IPC_PAYLOAD_HARD_MAX ? IPC_PAYLOAD_HARD_MAX
                                                         : sizes[k];
        uint64_t rate = 0, again = 0;

        if (bench_post(&tx, &rx, probe, msgs, window, &rate, &again) != 0) {
            rc = 1;
            goto out_stop;
        }
        if (json) {
            printf("    { \"payload\": %zu, \"messages\": %" PRIu64
                   ", \"per_sec\": %" PRIu64 ", \"eagain\": %" PRIu64
                   " }%s\n",
                   probe, msgs, rate, again,
                   (k + 1 == sizeof(sizes) / sizeof(sizes[0])) ? "" : ",");
        } else {
            printf("  %6zu B   %11" PRIu64 " msg/s   %" PRIu64
                   " EAGAIN retries\n",
                   probe, rate, again);
        }
    }
    if (json) {
        printf("  ],\n");
    }

    lat_buf = calloc(lat_rounds ? (size_t)lat_rounds : 1, sizeof(uint64_t));
    if (lat_buf == NULL) {
        fprintf(stderr, "bench: out of memory\n");
        rc = 1;
        goto out_stop;
    }
    if (!json) {
        printf("\n-- synchronous round trip (ipc_send_timeout, one waiter)\n");
    }
    {
        uint64_t again = 0;

        if (bench_send(&tx, &rx, payload, lat_rounds, lat_buf, &again) != 0) {
            rc = 1;
            goto out_stop;
        }
        qsort(lat_buf, (size_t)lat_rounds, sizeof(uint64_t), cmp_u64);
        if (!json) {
            printf("  %zu B payload, %" PRIu64 " calls, %" PRIu64
                   " EAGAIN retries\n",
                   payload, lat_rounds, again);
        }
        report_latency(lat_buf, (size_t)lat_rounds, json);
    }

    if (!json) {
        printf("\n-- broadcast fan-out (ipc_broadcast, one live peer)\n");
    }
    {
        uint64_t per_sec = 0, again = 0;

        if (bench_broadcast(&tx, &rx, payload, bcast_rounds, window, &per_sec,
                            &again) != 0) {
            rc = 1;
            goto out_stop;
        }
        if (json) {
            printf("  \"broadcast_rounds\": %" PRIu64
                   ", \"broadcast_per_sec\": %" PRIu64
                   ", \"broadcast_eagain\": %" PRIu64 ",\n",
                   bcast_rounds, per_sec, again);
        } else {
            printf("  %" PRIu64 " rounds, %" PRIu64 " bcast/s, %" PRIu64
                   " EAGAIN retries\n", bcast_rounds, per_sec, again);
        }
    }

    {
        ipc_stats_t st, rst;

        ipc_get_stats(tx.ctx, &st);
        ipc_get_stats(rx.ctx, &rst);
        if (json) {
            printf("  \"tx_stats\": { \"attempts\": %" PRIu64
                   ", \"enqueued\": %" PRIu64 ", \"failed\": %" PRIu64
                   ", \"bcast_targets\": %" PRIu64 ", \"eagain\": %" PRIu64
                   ", \"reply_matched\": %" PRIu64 " },\n"
                   "  \"rx_stats\": { \"read\": %" PRIu64
                   ", \"delivered\": %" PRIu64 ", \"cb_dropped\": %" PRIu64
                   ", \"rejected\": %" PRIu64 " }\n}\n",
                   st.send_attempts, st.send_enqueued, st.send_failed,
                   st.broadcast_targets, st.eagain_count, st.reply_matched,
                   rst.recv_read, rst.recv_delivered, rst.cb_dropped,
                   rst.recv_rejected);
        } else {
            printf("\n-- tx stats: attempts=%" PRIu64 " enqueued=%" PRIu64
                   " failed=%" PRIu64 " bcast_targets=%" PRIu64
                   " eagain=%" PRIu64 " reply_matched=%" PRIu64 "\n",
                   st.send_attempts, st.send_enqueued, st.send_failed,
                   st.broadcast_targets, st.eagain_count, st.reply_matched);
            /* Deliberately printed: if cb_dropped is non-zero the receiver
             * lost events, and a "delivered" count below `msgs` is then a
             * statement about loss, not about speed. */
            printf("-- rx stats: read=%" PRIu64 " delivered=%" PRIu64
                   " cb_dropped=%" PRIu64 " rejected=%" PRIu64 "\n",
                   rst.recv_read, rst.recv_delivered, rst.cb_dropped,
                   rst.recv_rejected);
        }
    }

    rc = 0;

out_stop:
    if (rx.tid_valid) {
        ipc_stop(rx.ctx);
    }
    if (tx.tid_valid) {
        ipc_stop(tx.ctx);
    }
    if (rx.tid_valid) {
        pthread_join(rx.tid, NULL);
    }
    if (tx.tid_valid) {
        pthread_join(tx.tid, NULL);
    }
out_unreg_both:
    ipc_unregister(tx.ctx);
    ipc_ctx_free(tx.ctx);
out_unreg_rx:
    ipc_unregister(rx.ctx);
    ipc_ctx_free(rx.ctx);
out_scratch:
    free(lat_buf);
    if (!keep) {
        /* Remove exactly the three entries we created, then the directory.
         * Deliberately no shell: a scratch path never needs one. */
        (void)unlink(sock_rx);
        (void)unlink(sock_tx);
        if (conf[0] != '\0') {
            (void)unlink(conf);
        }
        (void)rmdir(g_dir);
    } else {
        fprintf(stderr, "bench: keeping scratch dir %s\n", g_dir);
    }
    free(g_buf);
    return rc;
}
